"""empty message

Revision ID: 956bd8c00995
Revises: 
Create Date: 2019-08-01 23:52:51.293623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '956bd8c00995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('isbn', table_name='book')
    op.drop_table('book')
    op.alter_column('client', 'client_key',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('client', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.create_unique_constraint(None, 'client', ['client_secret'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.alter_column('client', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('client', 'client_key',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('pengarang', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('penerbit', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('harga', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('url_picture', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name='book_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('isbn', 'book', ['isbn'], unique=True)
    # ### end Alembic commands ###
